#
# Site settings
title: Thiago Medeiros
email: thsouzza@gmail.com
description: Thiago's personal website.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
url: "http://mthiiago.com" # the base hostname & protocol for your site
twitter_username: medeirosthiiago
github_username:  medeirosthiiago

# Build settings
markdown: kramdown
permalink: /:title
