# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Minimal
email: thsouzza@gmail.com
description: "Esse é um blog minimalista criado para aprender como funciona
    essa ferramenta linda que é o Jekyll."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
twitter_username: medeirosthiiago
github_username:  medeirosthiiago

# Build settings
markdown: kramdown
# permalink: /:categories/:year/:month/:day/:title
permalink: /:title
